/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package people.manager.view;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import people.manager.controller.Controller;
import people.manager.controller.ControllerCliente;
import people.manager.controller.ControllerProduto;
import people.manager.controller.ControllerFuncionario;
import people.manager.exception.ClienteNaoEncontradoException;
import people.manager.exception.ProdutoNaoEncontradoException;
import people.manager.exception.VendedorNaoEncontradoException;
import people.manager.model.Cliente;
import people.manager.model.Produto;
import people.manager.model.Venda;
import people.manager.model.Funcionario;

/**
 *
 * @author marcos
 */
public class TelaVenda extends javax.swing.JFrame {

    private JTable table;
    private final ArrayList<Produto> produtos;

    /**
     * Creates new form TelaVenda
     *
     * @param title
     */
    public TelaVenda(String title) {
        super(title);
        botaoX();
        produtos = new ArrayList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTOTAL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeVendedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCOdBarra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldValorUnitario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldQuantidadeVenda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jButtonAdicionar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldQuantidadeEstoque = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIDProduto = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldIDCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldIDVendedor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Total:");

        jTextFieldTOTAL.setEditable(false);
        jTextFieldTOTAL.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jTextFieldTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTOTALActionPerformed(evt);
            }
        });

        jLabel2.setText("Info. Cliente");

        jTextFieldNomeCliente.setEditable(false);
        jTextFieldNomeCliente.setToolTipText("Nome do Cliente");

        jLabel3.setText("Info. Vendedor");

        jTextFieldNomeVendedor.setEditable(false);
        jTextFieldNomeVendedor.setToolTipText("Nome do vendedor");
        jTextFieldNomeVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeVendedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Cod. Barra:");

        jTextFieldCOdBarra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCOdBarraFocusLost(evt);
            }
        });
        jTextFieldCOdBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCOdBarraActionPerformed(evt);
            }
        });

        jLabel5.setText("Produto:");

        jLabel6.setText("Valor Un.:");

        jTextFieldValorUnitario.setEditable(false);

        jLabel7.setText("Quantidade:");

        jTextFieldQuantidadeVenda.setText("1");
        jTextFieldQuantidadeVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldQuantidadeVendaFocusLost(evt);
            }
        });
        jTextFieldQuantidadeVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantidadeVendaActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor Total:");

        jTextFieldValorTotal.setEditable(false);

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jLabel9.setText("Quant. Estoque:");

        jTextFieldQuantidadeEstoque.setEditable(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/people/manager/view/search(1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/people/manager/view/search(1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/people/manager/view/search(1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setText("ID:");

        jTextFieldIDProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDProdutoActionPerformed(evt);
            }
        });

        jButton5.setText("Remover Item");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setText("ID:");

        jTextFieldIDCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIDClienteFocusLost(evt);
            }
        });
        jTextFieldIDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDClienteActionPerformed(evt);
            }
        });

        jLabel12.setText("Nome:");

        jLabel13.setFont(new java.awt.Font("Andale Mono", 0, 10)); // NOI18N
        jLabel13.setText("Informações venda");

        jLabel14.setText("ID:");

        jTextFieldIDVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDVendedorActionPerformed(evt);
            }
        });

        jLabel15.setText("Nome:");

        jButton6.setText("Remover tudo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setText("Finalizar Venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdicionar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCOdBarra)
                                    .addComponent(jTextFieldQuantidadeEstoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldValorUnitario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(6, 6, 6)
                                        .addComponent(jTextFieldQuantidadeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldValorTotal))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNomeProduto))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldIDVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                    .addComponent(jTextFieldIDCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNomeVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNomeCliente))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldIDVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldCOdBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jTextFieldIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldQuantidadeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))))
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTOTALActionPerformed

    private void jTextFieldCOdBarraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCOdBarraFocusLost

    }//GEN-LAST:event_jTextFieldCOdBarraFocusLost

    private void jTextFieldNomeVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeVendedorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Cliente c = ControllerCliente.buscarClienteInterface();
        if (c != null && c.isAtivo()) {
            jTextFieldIDCliente.setText(c.getId() + "");
            jTextFieldNomeCliente.setText(c.getNome());
        } else if (c != null && !c.isAtivo()) {
            JOptionPane.showMessageDialog(null, "Esse cliente não pode fazer compras.\nCliente dasativado.");
        } else {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        if (!jTextFieldIDProduto.getText().trim().equals("") && !jTextFieldNomeProduto.getText().trim().equals("")) {
            try {

                ArrayList<Produto> e = ControllerProduto.buscarNome(1, jTextFieldIDProduto.getText().trim());
                if (e.get(0).getQuantidade() > 0 && e.get(0).getQuantidade() >= Integer.parseInt(jTextFieldQuantidadeVenda.getText().trim())) {
                    if (e.get(0).getQuantidade() <= Integer.parseInt(Controller.getConfiguracao().getProperty("quantidade.min_estoque"))) {
                        JOptionPane.showMessageDialog(null, "A quantidade de produto está abaixo do minimo");
                    }
                    e.get(0).setQuantidade(Integer.parseInt(jTextFieldQuantidadeVenda.getText().trim()));
                    produtos.add((Produto) e.get(0));
                    ControllerProduto.removerEstoque(e.get(0).getId(), e.get(0).getQuantidade());
                    criarTabela(produtos);
                } else {
                    JOptionPane.showMessageDialog(null, "Não há quantidade suficiente de produto no estoque");
                }
            } catch (ProdutoNaoEncontradoException ex) {
                Logger.getLogger(TelaVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pesquise um produto para ser adicionado");
        }
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jTextFieldCOdBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCOdBarraActionPerformed
        new Thread() {
            @Override
            public void run() {
                try {
                    ArrayList<Produto> p = ControllerProduto.buscarNome(2, jTextFieldCOdBarra.getText().trim());
                    if (!p.isEmpty()) {
                        jTextFieldNomeProduto.setText(p.get(0).getNome());
                        jTextFieldIDProduto.setText(p.get(0).getId() + "");
                        jTextFieldValorUnitario.setText(String.format("%.2f", p.get(0).getValorVenda()));
                        jTextFieldQuantidadeEstoque.setText(p.get(0).getQuantidade() + "");
                        jTextFieldValorTotal.setText(String.format("%.2f", p.get(0).getValorVenda()));
//                        jTextFieldQuantidadeVendaFocusLost(evt);
                        jButtonAdicionarActionPerformed(evt);
                        limparCampos();
                    }
                } catch (ProdutoNaoEncontradoException ex) {
                    Logger.getLogger(TelaVenda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }.start();
    }//GEN-LAST:event_jTextFieldCOdBarraActionPerformed

    private void jTextFieldQuantidadeVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeVendaFocusLost
        if (!jTextFieldQuantidadeVenda.getText().isEmpty()) {
            jTextFieldValorTotal.setText(String.format("%.2f", Double.parseDouble(jTextFieldValorUnitario.getText().trim().replace(',', '.')) * Double.parseDouble(jTextFieldQuantidadeVenda.getText().trim())));
        }

    }//GEN-LAST:event_jTextFieldQuantidadeVendaFocusLost

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (table != null) {
            if (table.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um item para remover");
            } else {

                Integer id = Integer.parseInt((String) table.getValueAt(table.getSelectedRow(), 0));
                Integer quant = Integer.parseInt((String) table.getValueAt(table.getSelectedRow(), 4));
                if (produtos.size() > 1) {
                    for (Produto obj : produtos) {
                        if (obj.getId().equals(id) && obj.getQuantidade().equals(quant)) {
                            ControllerProduto.adicionaEstoque(id, obj.getQuantidade());
                            produtos.remove(obj);
                            break;
                        }
                    }
                } else {
                    produtos.clear();
                }

                criarTabela(produtos);

            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldIDProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDProdutoActionPerformed
        new Thread() {
            @Override
            public void run() {
                if (!jTextFieldIDProduto.getText().trim().equals("")) {
                    try {
                        ArrayList<Produto> p = ControllerProduto.buscarNome(1, jTextFieldIDProduto.getText().trim());
                        if (p != null && !p.isEmpty()) {
                            jTextFieldNomeProduto.setText(p.get(0).getNome());
                            jTextFieldCOdBarra.setText(p.get(0).getCodigoBarra());
                            jTextFieldValorUnitario.setText(String.format("%.2f", p.get(0).getValorVenda()));
                            jTextFieldQuantidadeEstoque.setText(p.get(0).getQuantidade() + "");
                            jTextFieldQuantidadeVenda.setText("1");
                        }
                    } catch (ProdutoNaoEncontradoException ex) {
                        JOptionPane.showMessageDialog(null, "Produto não encontrado");
                    }
                }
            }
        }.start();
    }//GEN-LAST:event_jTextFieldIDProdutoActionPerformed

    private void jTextFieldQuantidadeVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeVendaActionPerformed
        jTextFieldQuantidadeVendaFocusLost(null);
    }//GEN-LAST:event_jTextFieldQuantidadeVendaActionPerformed

    private void jTextFieldIDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDClienteActionPerformed
        if (!jTextFieldIDCliente.getText().trim().isEmpty()) {
            try {
                ArrayList<Cliente> c = ControllerCliente.buscarCliente(3, jTextFieldIDCliente.getText().trim());
                if (c.get(0).isAtivo()) {
                    jTextFieldNomeCliente.setText(c.get(0).getNome() + " " + c.get(0).getSobrenome());
                } else {
                    jTextFieldIDCliente.setText("");
                    JOptionPane.showMessageDialog(null, "Esse cliente não pode fazer compras.\nCliente dasativado.");
                }

            } catch (ClienteNaoEncontradoException ex) {
                JOptionPane.showMessageDialog(null, "Cliente não encontrado");
            }
        }
    }//GEN-LAST:event_jTextFieldIDClienteActionPerformed

    private void jTextFieldIDClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIDClienteFocusLost

    }//GEN-LAST:event_jTextFieldIDClienteFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Funcionario v = ControllerFuncionario.buscarFuncionarioInterface();
        if (v.isAtivo()) {
            jTextFieldIDVendedor.setText(v.getId() + "");
            jTextFieldNomeVendedor.setText(v.getNome() + " " + v.getSobrenome());
        } else {
            jTextFieldIDVendedor.setText("");
            JOptionPane.showMessageDialog(null, "Esse vendedor não pode vender.\nVendedor dasativado.");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        produtos.forEach((produto) -> {
            ControllerProduto.adicionaEstoque(produto.getId(), produto.getQuantidade());
        });
        this.produtos.clear();
        criarTabela(produtos);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextFieldIDVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDVendedorActionPerformed
        if (!jTextFieldIDVendedor.getText().trim().isEmpty()) {
            try {
                ArrayList<Funcionario> l = ControllerFuncionario.buscarFuncionario(2, jTextFieldIDVendedor.getText().trim());
                if (l.get(0).isAtivo()) {
                    jTextFieldNomeVendedor.setText(l.get(0).getNome() + " " + l.get(0).getSobrenome());
                } else {
                    jTextFieldIDVendedor.setText("");
                    JOptionPane.showMessageDialog(null, "Esse vendedor não pode vender.\nVendedor dasativado.");
                }

            } catch (VendedorNaoEncontradoException ex) {
                Logger.getLogger(TelaVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jTextFieldIDVendedorActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Produto p = ControllerProduto.buscarProdutoInterface();
        if (p != null) {
            jTextFieldCOdBarra.setText(p.getCodigoBarra());
            jTextFieldNomeProduto.setText(p.getNome());
            jTextFieldIDProduto.setText(p.getId() + "");
            jTextFieldValorUnitario.setText(String.format("%.2f", p.getValorVenda()));
            jTextFieldQuantidadeEstoque.setText(p.getQuantidade() + "");
            jTextFieldValorTotal.setText(String.format("%.2f", p.getValorVenda()));
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Venda venda = new Venda(0, "NULO", Integer.parseInt(jTextFieldIDCliente.getText()), Integer.parseInt(jTextFieldIDVendedor.getText()), produtos, Double.parseDouble(jTextFieldTOTAL.getText().replace("R$", "").trim().replace(",", ".")), "", 0.00, 0.00, "PENDENTE");
        TelaFinalizarVenda tfv = new TelaFinalizarVenda("Finalizar Venda", venda, this);
        Main.guardarJanela(tfv);
        tfv.setLocationRelativeTo(null);
        tfv.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void criarTabela(ArrayList<Produto> produto) {
        String[] colunas = {"ID", "NOME", "COD. BARRA", "VALOR UNIT", "QUANTIDADE", "VALOR TOTAL"};
        List<String[]> lista = new ArrayList<>();
        Double totalCompras = 0.0;
        for (Produto p : produto) {
            lista.add(new String[]{p.getId().toString(), p.getNome(), p.getCodigoBarra(), String.format("%.2f", p.getValorVenda()), p.getQuantidade().toString(), String.format("%.2f", Double.parseDouble(p.getQuantidade() + "") * Double.parseDouble(p.getValorVenda() + ""))});
            totalCompras += p.getQuantidade() * p.getValorVenda();
        }
        table = new JTable();
        DefaultTableModel model = new DefaultTableModel(lista.toArray(new String[lista.size()][]), colunas);
        table.setModel(model);
        jScrollPane1.setViewportView(table);
        jTextFieldTOTAL.setForeground(Color.red);
        jTextFieldTOTAL.setText(String.format("R$ %.2f", totalCompras));

    }

    /**
     * Limpa os todos campos relacionados aos produtos.
     */
    private void limparCampos() {
        jTextFieldNomeProduto.setText("");
        jTextFieldIDProduto.setText("");
        jTextFieldValorUnitario.setText("");
        jTextFieldQuantidadeEstoque.setText("");
        jTextFieldValorTotal.setText("");
        jTextFieldCOdBarra.setText("");
        jTextFieldQuantidadeVenda.setText("1");
    }

    private void botaoX() {
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (!produtos.isEmpty()) {
                    int resposta = JOptionPane.showConfirmDialog(null, "Se você fechar essa janela toda a compra será cancelada.\nDeseja continuar?", "Fechar compra", JOptionPane.YES_NO_OPTION);
                    if (resposta == 0) {
                        new Thread() {
                            @Override
                            public void run() {
                                produtos.forEach((produto) -> {
                                    ControllerProduto.adicionaEstoque(produto.getId(), produto.getQuantidade());
                                });
                            }
                        }.start();
                        dispose();
                    }
                } else {
                    dispose();
                }

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldCOdBarra;
    private javax.swing.JTextField jTextFieldIDCliente;
    private javax.swing.JTextField jTextFieldIDProduto;
    private javax.swing.JTextField jTextFieldIDVendedor;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldNomeVendedor;
    private javax.swing.JTextField jTextFieldQuantidadeEstoque;
    private javax.swing.JTextField jTextFieldQuantidadeVenda;
    private javax.swing.JTextField jTextFieldTOTAL;
    private javax.swing.JTextField jTextFieldValorTotal;
    private javax.swing.JTextField jTextFieldValorUnitario;
    // End of variables declaration//GEN-END:variables
}
