/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package people.manager.view;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import people.manager.controller.Controller;
import people.manager.controller.ControllerProduto;
import people.manager.exception.ProdutoNaoEncontradoException;
import people.manager.model.Produto;

/**
 *
 * @author marcos
 */
public class TelaAdicRemEstoque extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicRemEstoque
     *
     * @param title
     */
    public TelaAdicRemEstoque(String title) {
        super(title);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodBarra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldQuantAtual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldQuantFutura = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAdicRem = new javax.swing.JTextField();
        jRadioButtonAdd = new javax.swing.JRadioButton();
        jRadioButtonRm = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        buttonGroup1.add(jRadioButtonAdd);
        buttonGroup1.add(jRadioButtonRm);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cod. Barra:");

        jTextFieldCodBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodBarraActionPerformed(evt);
            }
        });

        jLabel2.setText("ID:");

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jLabel3.setText("Produto:");

        jTextFieldProduto.setEditable(false);

        jLabel4.setText("Quant. Atual:");

        jTextFieldQuantAtual.setEditable(false);
        jTextFieldQuantAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantAtualActionPerformed(evt);
            }
        });

        jLabel5.setText("Quant. Futura:");

        jTextFieldQuantFutura.setEditable(false);

        jLabel6.setText("Qu. Adic/Rem:");

        jTextFieldAdicRem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldAdicRem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAdicRemFocusLost(evt);
            }
        });
        jTextFieldAdicRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdicRemActionPerformed(evt);
            }
        });

        jRadioButtonAdd.setSelected(true);
        jRadioButtonAdd.setText("Adicionar");
        jRadioButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAddActionPerformed(evt);
            }
        });

        jRadioButtonRm.setText("Remover");
        jRadioButtonRm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRmActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gravar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/people/manager/view/search(1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldProduto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldQuantAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldQuantFutura))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4)
                                .addComponent(jTextFieldID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(8, 8, 8)
                                .addComponent(jTextFieldAdicRem, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonRm)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldQuantFutura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldQuantAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAdicRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButtonAdd)
                    .addComponent(jRadioButtonRm))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAddActionPerformed
        jTextFieldAdicRemActionPerformed(null);
    }//GEN-LAST:event_jRadioButtonAddActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        if (!jTextFieldID.getText().trim().equals("")) {
            try {
                ArrayList<Produto> p = ControllerProduto.buscarNome(1, jTextFieldID.getText().trim());
                jTextFieldCodBarra.setText(p.get(0).getCodigoBarra());
                jTextFieldID.setText(p.get(0).getId() + "");
                jTextFieldProduto.setText(p.get(0).getNome());
                jTextFieldQuantAtual.setText(p.get(0).getQuantidade() + "");
            } catch (ProdutoNaoEncontradoException ex) {
                Logger.getLogger(TelaAdicRemEstoque.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldQuantAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantAtualActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Produto p = ControllerProduto.buscarProdutoInterface();
        if (p != null) {
            jTextFieldCodBarra.setText(p.getCodigoBarra());
            jTextFieldID.setText(p.getId() + "");
            jTextFieldProduto.setText(p.getNome());
            jTextFieldQuantAtual.setText(p.getQuantidade() + "");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldAdicRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdicRemActionPerformed
        if (!jTextFieldAdicRem.getText().trim().equals("")) {
            if (jRadioButtonAdd.isSelected()) {
                jTextFieldAdicRem.setText(jTextFieldAdicRem.getText().trim().replace("-", ""));
                jTextFieldQuantFutura.setText(Integer.parseInt(jTextFieldQuantAtual.getText().trim()) + Integer.parseInt(jTextFieldAdicRem.getText().trim()) + "");
                // Teste valor negativo
                if(Integer.parseInt(jTextFieldQuantFutura.getText().trim()) < 0){
                    JOptionPane.showMessageDialog(null, "Valor futuro não pode ser negativo.");
                    jTextFieldQuantFutura.setText("");
                }
                    
            } else {
                jTextFieldAdicRem.setText(jTextFieldAdicRem.getText().trim().replace("+", ""));
                jTextFieldQuantFutura.setText(Integer.parseInt(jTextFieldQuantAtual.getText().trim()) - Integer.parseInt(jTextFieldAdicRem.getText().trim()) + "");
                // Teste valor negativo
                if(Integer.parseInt(jTextFieldQuantFutura.getText().trim()) < 0){
                    JOptionPane.showMessageDialog(null, "Valor futuro não pode ser negativo.");
                    jTextFieldQuantFutura.setText("");
                }
            }
        }
    }//GEN-LAST:event_jTextFieldAdicRemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jRadioButtonAdd.isSelected() && !jTextFieldQuantFutura.getText().trim().equals("")) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que você quer ADICIONAR " + jTextFieldAdicRem.getText().trim() + " ao\nproduto com ID: " + jTextFieldID.getText().trim() + "?") == 0) {
                ControllerProduto.adicionaEstoque(Integer.parseInt(jTextFieldID.getText().trim()), Integer.parseInt(jTextFieldAdicRem.getText().trim()));
                Controller.novoLog(" adicionou "+jTextFieldAdicRem.getText().trim()+" no estoque do produto ID: "+jTextFieldID.getText().trim());
                JOptionPane.showMessageDialog(null, "Foi adicionado a quantidade ao produto.");
                
            }
        } else if (!jRadioButtonAdd.isSelected() && !jTextFieldQuantFutura.getText().trim().equals("")) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que você quer REMOVER " + jTextFieldAdicRem.getText().trim() + " ao\nproduto com ID:" + jTextFieldID.getText().trim() + "?") == 0) {
                ControllerProduto.removerEstoque(Integer.parseInt(jTextFieldID.getText().trim()), Integer.parseInt(jTextFieldAdicRem.getText().trim()));
                JOptionPane.showMessageDialog(null, "Foi removido a quantidade do produto.");
                Controller.novoLog(" retirou "+jTextFieldAdicRem.getText().trim()+" do estoque do produto ID: "+jTextFieldID.getText().trim());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Valor futuro deve estar preenchido.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldAdicRemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAdicRemFocusLost
        jTextFieldAdicRemActionPerformed(null);
    }//GEN-LAST:event_jTextFieldAdicRemFocusLost

    private void jRadioButtonRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRmActionPerformed
        jTextFieldAdicRemActionPerformed(null);
    }//GEN-LAST:event_jRadioButtonRmActionPerformed

    private void jTextFieldCodBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodBarraActionPerformed
        if (!jTextFieldCodBarra.getText().trim().equals("")) {
            try {
                ArrayList<Produto> p = ControllerProduto.buscarNome(2, jTextFieldCodBarra.getText().trim());
                jTextFieldCodBarra.setText(p.get(0).getCodigoBarra());
                jTextFieldID.setText(p.get(0).getId() + "");
                jTextFieldProduto.setText(p.get(0).getNome());
                jTextFieldQuantAtual.setText(p.get(0).getQuantidade() + "");
            } catch (ProdutoNaoEncontradoException ex) {
                Logger.getLogger(TelaAdicRemEstoque.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTextFieldCodBarraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButtonAdd;
    private javax.swing.JRadioButton jRadioButtonRm;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldAdicRem;
    private javax.swing.JTextField jTextFieldCodBarra;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldQuantAtual;
    private javax.swing.JTextField jTextFieldQuantFutura;
    // End of variables declaration//GEN-END:variables
}
