/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package people.manager.view;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import people.manager.controller.Controller;
import people.manager.controller.ControllerCliente;
import people.manager.controller.ControllerProduto;
import people.manager.exception.ClienteNaoEncontradoException;
import people.manager.exception.ProdutoNaoEncontradoException;
import people.manager.model.Produto;

/**
 *
 * @author marcos
 */
public class TelaBuscaProduto extends javax.swing.JFrame {

    private JTable table;
    /**
     * Creates new form TelaBuscaProduto
     * @param title
     */
    public TelaBuscaProduto(String title) {
        super(title);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pesquisa:");

        jTextFieldBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscaKeyPressed(evt);
            }
        });

        jButton1.setText("Remover");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 176, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscaKeyPressed
        try {
            ArrayList a = ControllerProduto.buscarNome(0, jTextFieldBusca.getText().trim());
            criarTabela(a);
        } catch (ProdutoNaoEncontradoException ex) {
        }
    }//GEN-LAST:event_jTextFieldBuscaKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (table != null) {
            ArrayList c;
            if (table.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um produto antes");
            } else {
                try {
                    c = ControllerProduto.buscarNome(1, (String)table.getValueAt(table.getSelectedRow(), 0));
                } catch (ProdutoNaoEncontradoException ex) {
                    Logger.getLogger(TelaBuscaCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (table != null) {
            ArrayList<Produto> c;
            if (table.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um produto antes");
            } else {
                try {
                    c = ControllerProduto.buscarNome(1, (String)table.getValueAt(table.getSelectedRow(), 0));
                    if(c.get(0).getQuantidade() > 0 && Controller.getUser().getLevel() == 1){
                        if(JOptionPane.showConfirmDialog(null, "O produto tem "+c.get(0).getQuantidade()+" itens no estoque.\nTem certeza que deseja remover?") == 0){
                            ControllerProduto.apagarProduto(c.get(0).getId());
                            JOptionPane.showMessageDialog(null, "Produto apagado");
                        }
                    } else if(c.get(0).getQuantidade() > 0 && Controller.getUser().getLevel() == 0){
                        JOptionPane.showMessageDialog(null, "Você não tem permissão para apagar produtos\nque tem quantidade maior que zero em estoque.");
                    } else {
                        if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover?") == 0){
                            ControllerProduto.apagarProduto(c.get(0).getId());
                            JOptionPane.showMessageDialog(null, "Produto apagado");
                        }
                    }
                } catch (ProdutoNaoEncontradoException ex) {
                    Logger.getLogger(TelaBuscaCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void criarTabela(ArrayList<Produto> produto) {
        String[] colunas = {"ID", "NOME", "COD. BARRA", "VALOR", "QUANTIDADE"};
        List<String[]> lista = new ArrayList<>();
        for (Produto p : produto) 
            lista.add(new String[]{p.getId().toString(), p.getNome(), p.getCodigoBarra(), p.getValorVenda().toString(), p.getQuantidade().toString()});
        table = new JTable();
        DefaultTableModel model = new DefaultTableModel(lista.toArray(new String[lista.size()][]), colunas);
        table.setModel(model);
        jScrollPane1.setViewportView(table);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBusca;
    // End of variables declaration//GEN-END:variables
}
