/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package people.manager.view;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import people.manager.controller.Controller;
import people.manager.controller.ControllerCliente;
import people.manager.exception.ClienteNaoEncontradoException;
import people.manager.model.Cliente;

/**
 *
 * @author marcos
 */
public class TelaRemoverCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaRemoverCliente
     * @param title
     */
    public TelaRemoverCliente(String title) {
        super(title);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBoxExcluir = new javax.swing.JCheckBox();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CPF:");

        jButton1.setText("Desativar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCheckBoxExcluir.setText("Excluir");
        jCheckBoxExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCPF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 161, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBoxExcluir, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxExcluir)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Cliente> c;
        try {
            c = ControllerCliente.buscarCliente(1, jTextFieldCPF.getText().trim());
            if(c.get(0).getSaldoDevedor() > 0.0){
                JOptionPane.showMessageDialog(null, "Cliente não pode ser removido, pois está devendo R$"+c.get(0).getSaldoDevedor()+".");
                return;
            }
            int resp = JOptionPane.showConfirmDialog(null, "Você tem total certeza disso? \n"
                + "Deseja desabilitar/remover "+c.get(0).getNome()+" "+c.get(0).getSobrenome()+" com CPF "+c.get(0).getCpf()+"?");
            if(resp == 0 && !jCheckBoxExcluir.isSelected()){
                ControllerCliente.desativarCliente(jTextFieldCPF.getText().trim());
                JOptionPane.showMessageDialog(null, "Cliente debilitado.");
                Controller.novoLog("desabilitou o cliente que contém o CPF "+jTextFieldCPF.getText().trim());
            }else if(resp == 0 && jCheckBoxExcluir.isSelected()){
                JOptionPane.showMessageDialog(null, "Sempre opte por usar a opção de "
                        + "desabilitar o cliente, caso \ncontrario isso pode trazer problemas no futuro.\n"
                        + "Será pedido senha de administrador em seguida.");
                TelaConfimacaoUserSenha t = new TelaConfimacaoUserSenha("Remover Cliente", jTextFieldCPF.getText().trim());
                t.setLocationRelativeTo(null);
                t.setVisible(true);
                
            }
        } catch (ClienteNaoEncontradoException ex) {
            JOptionPane.showMessageDialog(null, "Cliente não existe.");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxExcluirActionPerformed
        if(jCheckBoxExcluir.isSelected())
            jButton1.setText("Remover");
        else
            jButton1.setText("Desativar");
    }//GEN-LAST:event_jCheckBoxExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
